package hardware

// Privileged disk *actions* (as opposed to the probes in the rest of this package):
// mounting and unmounting a partition, and safely removing a whole disk. The work is
// done by the hostek-diskctl wrapper (generated by `hostek setup`); this file is the
// guard rail in front of it and the translator of its verdicts.
//
// Three rules hold everywhere below:
//
//   - Names are kernel device names ("sdb", "nvme0n1p2"), never paths. Anything
//     path-shaped is rejected before it can become a shell argument.
//   - The device must be something the kernel lists *right now*, of the expected kind
//     (whole disk for eject, partition for mount/unmount). That is what stops "sda1"
//     being ejected or "sda" being mounted.
//   - The system's own storage is off limits: the root disk cannot be ejected and the
//     mounts the OS runs from cannot be unmounted. Enforced here AND in the wrapper —
//     each has to be safe on its own, since sudo makes the wrapper reachable directly.
//
// Failures that only the wrapper can diagnose (a busy mount, a filesystem the kernel
// won't touch) come back as its own message, which is passed through to the user:
// "cannot unmount /srv — target is busy" beats a generic "operation failed".

import (
	"context"
	"errors"
	"fmt"
	"os/exec"
	"regexp"
	"strings"
	"time"

	"hostek/internal/diskutil"
)

const diskctlWrapper = "/usr/local/sbin/hostek-diskctl"

// diskctlTimeout is generous next to the probe timeouts: these operations sync dirty
// pages and unmount filesystems, which on a busy spinning disk takes seconds.
const diskctlTimeout = 60 * time.Second

var (
	// ErrUnknownDevice — no such disk/partition, or a name that isn't one.
	ErrUnknownDevice = errors.New("unknown device")
	// ErrSystemDisk — the disk the OS runs from. Never ejectable.
	ErrSystemDisk = errors.New("refusing to eject the system disk")
	// ErrDiskOpFailed — the wrapper refused or failed; wrapped with its message.
	ErrDiskOpFailed = errors.New("disk operation failed")
)

// devNameRe matches a kernel device name ("sda", "nvme0n1p2"). Its job is to reject
// anything path-shaped ("../../dev/sda", "/dev/sda") up front.
var devNameRe = regexp.MustCompile(`^[a-zA-Z0-9]+$`)

// Eject safely removes the whole disk `name` ("sdb" — not "/dev/sdb", not "sdb1"):
// its filesystems are unmounted, buffers flushed, and the device detached from the
// kernel. The disk then leaves the Disks tab; bringing it back takes a bus rescan or
// a reboot, which is the point of an eject rather than a shortcoming of it.
//
// On a board without working SATA hotplug this is also the *only* clean way to pull a
// drive: yanking it live leaves the stale node the Disks tab flags as Unreachable.
func (c *Collector) Eject(name string) error {
	if err := checkName(name); err != nil {
		return err
	}
	if !isWholeDisk(name) {
		return fmt.Errorf("%w: %s is not a whole disk", ErrUnknownDevice, name)
	}
	if root := diskutil.RootDevice(); root != "" && name == root {
		return ErrSystemDisk
	}
	return diskctl("eject", name)
}

// Mount mounts the partition `name` ("sdb1") and returns where it landed. The wrapper
// honours an /etc/fstab entry when one exists, and otherwise mounts under /media/hostek/
// with nosuid,nodev — a drive someone just plugged in must not be able to bring its own
// setuid binaries or device nodes into the system.
func (c *Collector) Mount(name string) (string, error) {
	if err := checkName(name); err != nil {
		return "", err
	}
	if !isPartition(name) {
		return "", fmt.Errorf("%w: %s is not a partition", ErrUnknownDevice, name)
	}
	out, err := diskctlOut("mount", name)
	if err != nil {
		return "", err
	}
	return out, nil // the wrapper prints the resulting mountpoint
}

// Unmount unmounts the partition `name`. The wrapper refuses the mounts the running
// system depends on (/, /boot, /usr, …), so this cannot be used to take the OS apart.
func (c *Collector) Unmount(name string) error {
	if err := checkName(name); err != nil {
		return err
	}
	if !isPartition(name) {
		return fmt.Errorf("%w: %s is not a partition", ErrUnknownDevice, name)
	}
	return diskctl("unmount", name)
}

// checkName rejects anything that is not a bare kernel device name.
func checkName(name string) error {
	if !devNameRe.MatchString(name) {
		return fmt.Errorf("%w: %q", ErrUnknownDevice, name)
	}
	return nil
}

// diskctl runs one wrapper verb, discarding its stdout.
func diskctl(verb, name string) error {
	_, err := diskctlOut(verb, name)
	return err
}

// diskctlOut runs one wrapper verb and returns its trimmed stdout. A failure carries
// the wrapper's stderr — the actionable half of the message.
func diskctlOut(verb, name string) (string, error) {
	out, errMsg, ok := runCmdCapture(diskctlTimeout, "sudo", "-n", diskctlWrapper, verb, "/dev/"+name)
	if !ok {
		return "", fmt.Errorf("%w: %s", ErrDiskOpFailed, errMsg)
	}
	return out, nil
}

// isWholeDisk reports whether the kernel currently lists `name` as a whole disk.
func isWholeDisk(name string) bool {
	for _, n := range wholeDiskNames() {
		if n == name {
			return true
		}
	}
	return false
}

// isPartition reports whether the kernel currently lists `name` as a partition. A
// whole disk is not a partition, so "sda" can never be routed into a mount call.
func isPartition(name string) bool {
	return strings.TrimSpace(readSysStr("/sys/class/block/"+name+"/partition")) != ""
}

// runCmdCapture runs a command and returns (stdout, stderr, ok). runCmd (hardware.go)
// drops stderr because a failed *probe* just means "no data"; a failed disk *action*
// has a reason the user is entitled to read.
func runCmdCapture(timeout time.Duration, name string, args ...string) (string, string, bool) {
	ctx, cancel := context.WithTimeout(context.Background(), timeout)
	defer cancel()
	var stdout, stderr strings.Builder
	cmd := exec.CommandContext(ctx, name, args...)
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr
	err := cmd.Run()
	out := strings.TrimSpace(stdout.String())
	if err == nil {
		return out, "", true
	}
	switch msg := strings.TrimSpace(stderr.String()); {
	case msg != "":
		return out, msg, false
	case ctx.Err() != nil:
		return out, "timed out", false
	default:
		return out, err.Error(), false
	}
}
